export const Projectdata = [
  {
    ProjectID: "0c9vdky2g3u4quyg3f",
    ProjectName: "Student Attendance Management",
    ProjectDescription: [
      "I developed a Student Attendance Management System using the MERN Stack (MongoDB, Express.js, React.js, Node.js). This system is designed with separate panels for both students and administrators. Key features of the system include:",
      "1. User Panel: Provides registration and login options for students. Students can view their attendance records, request leave, and update their profiles through this panel.",
      "2. Admin Panel: Allows administrators to manage student records, track attendance, handle leave approvals, and assign grades.",
      "3. Secure Authentication: Implemented secure authentication and role-based access control to ensure data security and privacy.",
      "4. Responsive Dashboard: A responsive dashboard that summarizes attendance records, leave requests, and student profiles for both administrators and students.",
      "5. Filter Options: Includes filter options like 'Last Week' and 'Last Month' to help users easily view their attendance history.",
      "This system provides an interactive and user-friendly interface that effectively assists educational institutions in managing student attendance.",
    ],
    ProjectImages: "Sam",
    ProjectTecnology: "MERN Stack (MongoDB - ExpressJS - ReactJS - NodeJS)",
    ProjectGithub:
      "https://github.com/Munawwar-Ishaq/StudentAttendanceFrontend.git",
    ProjectLiveURL: "https://student-att.netlify.app",
    UploadDate: "11 September 2024",
    ProjectfrontendLiberies: [
      "Framework - React",
      "module - react-router-dom",
      "module - @fortawesome/fontawesome-free",
      "module - js-cookie",
      "module - axios",
    ],
    projectbackendLiberies: [
      "module - express",
      "module - mongoose",
      "module - body-parser",
      "module - jsonwebtoken",
      "module - dotenv",
      "module - cors",
      "module - node-corn",
    ],
    Database: ["MongoDB"],
    ProjectContent:
      "A comprehensive MERN Stack-based application developed to streamline and automate the process of managing student attendance. The system features a user-friendly interface for students and an efficient dashboard for administrators.",
  },
  {
    ProjectID: "0f98g4k12x5yj7f3n5",
    ProjectName: "FoodiOf",
    ProjectDescription: [
      "FoodiOf is a modern restaurant website showcasing a diverse menu, popular dishes, team details, and more. It is designed to provide a seamless experience for customers, featuring beautiful imagery and an intuitive layout. Key features of the website include:",
      "1. Responsive Design: The website is fully responsive, ensuring a great experience on both desktop and mobile devices. It uses attractive background images and well-placed content sections.",
      "2. Dynamic Menu Display: The menu page features dynamic content that showcases various categories like Breakfast, Lunch, Dinner, and Desserts. It includes images, titles, and categories for easy browsing.",
      "3. High-Quality Images: Each menu item is paired with a high-quality image that matches the dish title, enhancing the user experience.",
      "4. User-Friendly Navigation: Easy-to-use navigation with a clear layout that guides users through different sections like 'About Us,' 'Menu,' 'Our Team,' and 'Contact Us.'",
      "5. Dark-Themed Background: The website uses dark-themed backgrounds for better visual appeal and to make content stand out.",
      "This website is perfect for any modern restaurant looking to create a strong online presence and attract customers with its aesthetically pleasing design.",
    ],
    ProjectImages: "FoodiOf",
    ProjectTecnology: "MERN Stack (MongoDB - ExpressJS - ReactJS - NodeJS)",
    ProjectGithub: "https://github.com/Munawwar-Ishaq/FoodiOf-Frontend.git",
    ProjectLiveURL: "https://foodiof.netlify.app",
    UploadDate: "13 September 2024",
    ProjectfrontendLiberies: [
      "Framework - React",
      "Tooling - Vite",
      "module - react-router-dom",
      "module - react-icons",
      "module - axios",
      "module - styled-components",
    ],
    projectbackendLiberies: [
      "module - express",
      "module - mongoose",
      "module - body-parser",
      "module - dotenv",
      "module - cors",
      "module - validator",
    ],
    Database: ["MongoDB"],
    ProjectContent:
      "A visually captivating restaurant website built using the MERN Stack that features an interactive and easy-to-navigate menu, stunning visuals, and comprehensive content sections that effectively represent a modern dining experience.",
  },
];
